### ISSUE TITLE
Battery voltage

### ISSUE THREAD

**Issue by elgerg** [Xinyuan-LilyGO/LILYGO-T8#1]
Hi,

What pin can I use to measure the remaining battery voltage?

Thanks

**Comment by kreier** [comment]
IO35 is connected to the battery voltage over a 100k/100k divider. Multiply the measured voltage there to get the battery voltage. See in the schematics:

![battery_T-8](https://user-images.githubusercontent.com/43933271/224524789-84b50ec5-fb32-42fc-9e64-3fd719926847.png)

**Comment by elgerg** [comment]
Oh wow. I forgot I raised this...
